mqtt:
  host: mqtt
  topic_prefix: frigate

version: 0.17-0

objects:
  track:
    - person
    - cat
    - car
    - bike
  filters:
    person:
      min_score: 0.8

detectors:
  onnx:
    type: onnx

model:
  model_type: yolo-generic
  width: 320
  height: 320
  input_tensor: nchw
  input_dtype: float
  path: /config/model_cache/yolov9-m-320.onnx
  labelmap_path: /labelmap/coco-80.txt

detect:
  enabled: true
  fps: 5

cameras:
  west-road-view-D1:
    enabled: true
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: 
            rtsp://admin:pass@192.168.1.201:554/cam/realmonitor?channel=1&subtype=0
          input_args: preset-rtsp-restream
          roles: [record]
        - path: 
            rtsp://admin:pass@192.168.1.201:554/cam/realmonitor?channel=1&subtype=1
          roles: [detect]
    detect:
      enabled: false
      width: 640
      height: 380

    motion: {}
  east-side-D2:
    enabled: true
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: 
            rtsp://admin:pass@192.168.1.202:554/cam/realmonitor?channel=1&subtype=0
          input_args: preset-rtsp-restream
          roles: [record]
        - path: 
            rtsp://admin:pass@192.168.1.202:554/cam/realmonitor?channel=1&subtype=1
          roles: [detect]
    detect:
      enabled: true
      width: 640
      height: 380

    motion:
      mask: 
        0,0,0.003,0.994,0.997,0.991,1,0,0.678,0,0.684,0.121,0.678,0.256,0.65,0.291,0.578,0.276,0.579,0.064,0.579,0

  porch-to-door-D3:
    enabled: true
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: 
            rtsp://admin:pass@192.168.1.203:554/cam/realmonitor?channel=1&subtype=0
          input_args: preset-rtsp-restream
          roles: [record]
        - path: 
            rtsp://admin:pass@192.168.1.203:554/cam/realmonitor?channel=1&subtype=1
          roles: [detect]
    detect:
      enabled: false
      width: 640
      height: 380

  porch-to-north-road-D4:
    enabled: true
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: 
            rtsp://admin:pass@192.168.1.204:554/cam/realmonitor?channel=1&subtype=0
          input_args: preset-rtsp-restream
          roles: [record]
        - path: 
            rtsp://admin:pass@192.168.1.204:554/cam/realmonitor?channel=1&subtype=1
          roles: [detect]
    detect:
      enabled: false
      width: 640
      height: 380

  porch-to-gateD5:
    enabled: true
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: 
            rtsp://admin:pass@192.168.1.205:554/cam/realmonitor?channel=1&subtype=0
          input_args: preset-rtsp-restream
          roles: [record]
        - path: 
            rtsp://admin:pass@192.168.1.205:554/cam/realmonitor?channel=1&subtype=1
          roles: [detect]
    detect:
      enabled: false
      width: 640
      height: 380

  west-side-road-D6:
    enabled: true
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: 
            rtsp://admin:pass@192.168.1.206:554/cam/realmonitor?channel=1&subtype=0
          input_args: preset-rtsp-restream
          roles: [record]
        - path: 
            rtsp://admin:pass@192.168.1.206:554/cam/realmonitor?channel=1&subtype=1
          roles: [detect]
    detect:
      width: 640
      height: 380
    zones: {}
    notifications:
      enabled: true
    motion:
      mask: 
        0.001,0.001,0.002,0.999,0.411,0.996,0.315,0.843,0.311,0.35,0.562,0.091,0.998,0.101,0.999,0.003
  terris-D7:
    enabled: true
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: 
            rtsp://admin:pass@192.168.1.207:554/cam/realmonitor?channel=1&subtype=0
          input_args: preset-rtsp-restream
          roles: [record]
        - path: 
            rtsp://admin:pass@192.168.1.207:554/cam/realmonitor?channel=1&subtype=1
          roles: [detect]
    detect:
      enabled: true
      width: 640
      height: 380
    notifications:
      enabled: true
    zones: {}
    motion:
      mask:
        - 0.002,0.008,0,0.395,0.083,0.383,0.097,0.283,0.108,0.2,0.286,0.007
        - 0.294,0,0.464,0.236,0.603,0.267,0.595,0.36,0.675,0.36,0.814,0.415,0.825,0.457,0.969,0.517,1,0.491,0.996,0.006
  east-side-D8:
    enabled: true
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: 
            rtsp://admin:pass@192.168.1.208:554/cam/realmonitor?channel=1&subtype=0
          input_args: preset-rtsp-restream
          roles: [record]
        - path: 
            rtsp://admin:pass@192.168.1.208:554/cam/realmonitor?channel=1&subtype=1
          roles: [detect]
    detect:
      enabled: false
      width: 640
      height: 380

    motion:
      mask: 
        0,0,0.003,0.987,0.312,0.996,0.478,0.609,0.531,0.499,0.646,0.537,0.652,0.827,0.984,0.854,0.998,0.847,0.998,0.003
record:
  enabled: true
  alerts:
    retain:
      days: 30
      mode: motion
  detections:
    retain:
      days: 30
      mode: motion

  continuous:
    days: 30
  motion:
    days: 30

semantic_search:
  enabled: false
  model_size: large

face_recognition:
  enabled: true
  model_size: large

lpr:
  enabled: false

classification:
  bird:
    enabled: false

notifications:
  enabled: true
  email: username@gmail.com
