version: '3'

services:
  uptime-kuma:
    container_name: uptime-kuma
    image: louislam/uptime-kuma
    restart: always
    environment:
      - TZ=Asia/Kolkata
    ports:
      - "3001:3001" # SSH
    volumes:
      - ./data:/home/uptime-kuma/data
      - ./scripts:/scripts
