version: '3'

services:
  crafty:
    container_name: crafty_container
    image: registry.gitlab.com/crafty-controller/crafty-4:latest
    restart: always
    environment:
      - TZ=Asia/Kolkata
    ports:
      - "8000:8000" # HTTP
      - "8443:8443" # HTTPS
      - "8123:8123" # DYNMAP
      - "19132:19132/udp" # BEDROCK
      - "25500-25600:25500-25600" # MC SERV PORT RANGE
    volumes:
      - /home/docker/data/crafty/backups:/crafty/backups
      - /home/docker/data/crafty/logs:/crafty/logs
      - /home/docker/data/crafty/servers:/crafty/servers
      - /home/docker/data/crafty/config:/crafty/app/config
      - /home/docker/data/crafty/import:/crafty/import
