services:
  ollama-server:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - /home/docker/data/ollama/ollama:/root/.ollama
    restart: unless-stopped
    environment:
      - gpus=all
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 1
            capabilities: [gpu]

