services:
  beszel-agent:
    image: henrygd/beszel-agent-nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - utility

    container_name: beszel-agent
    restart: unless-stopped
    env_file:
      - '.env'
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /home/docker/data/beszel/beszel_agent_data:/var/lib/beszel-agent
      # monitor other disks / partitions by mounting a folder in /extra-filesystems
      - /home/docker/data/.beszel:/extra-filesystems/data-partition:ro
      - /home/docker/hdd/.beszel:/extra-filesystems/hdd
    environment:
      LISTEN: 45876
      KEY: ${KEY}
      TOKEN: ${TOKEN}
      HUB_URL: ${HUB_URL}
