version: '3'

services:
  borg:
    container_name: borg_container
    image: borg-server
    build: .
    restart: always
    environment:
      - TZ=Asia/Kolkata
    ports:
      - "2222:22" # SSH
    volumes:
      - /home/docker/data/borg/repositories:/home/borg/repo
      - /home/docker/data/borg/ssh:/home/borg/.ssh

