# borg-server/Dockerfile
FROM debian:bullseye-slim

RUN apt-get update && \
    apt-get install -y openssh-server borgbackup && \
    mkdir /var/run/sshd && \
    apt-get clean

# Create a borg user
RUN useradd -m -s /bin/bash borg && \
    mkdir -p /home/borg/.ssh/authorized_keys && \
    chmod 600 /home/borg/.ssh -R

# Copy authorized_keys at build time (you can use bind mounts instead)
# COPY authorized_keys/borg.pub /home/borg/.ssh/authorized_keys

RUN chmod 600 /home/borg/.ssh -R && \
    chown -R borg:borg /home/borg/.ssh

# Create a volume mount point
RUN mkdir -p /home/borg/repo && chown borg:borg /home/borg/repo

EXPOSE 22

COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

ENTRYPOINT ["./entrypoint.sh"]
#CMD ["/usr/sbin/sshd", "-D"]
