version: '3.3'
services:
  stirling-pdf:
    image: frooodle/s-pdf:latest
    ports:
      - '8080:8080'
#   volumes:
#     - /location/of/trainingData:/usr/share/tesseract-ocr/4.00/tessdata #Required for extra OCR languages
#     - /location/of/extraConfigs:/configs
#     - /location/of/customFiles:/customFiles/

