services:
  beszel-agent:
    image: "henrygd/beszel-agent"
    container_name: "beszel-agent"
    restart: unless-stopped
    network_mode: host
    volumes:
       - /var/run/docker.sock:/var/run/docker.sock:ro
      # monitor other disks / partitions by mounting a folder in /extra-filesystems
       - /home/docker/data/.beszel:/extra-filesystems/sda1:ro
    environment:
      LISTEN: 45876
      KEY: "enter your public key here from the beszel hub"

